[package]
name = "basic-http-rs"
version = "0.2.1"
edition = "2024"

[dependencies]
argh = "0.1.19"
async-trait = "0.1.92"
brotli = "9.0.0"
flate2 = "1.1.10"
mime_guess = "2.0.5"
tokio = { version = "1.53.1", features = ["full"] }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true
